# Generated by Django 5.0.3 on 2024-05-31 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_brand_name_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='store.specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(through='store.ProductSpecification', to='store.specification'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
